#spring:
#  application:
#    name: sell-mail-gateway
#  redis:
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 1
#        #连接池中的最大空闲连接
#        max-idle: 8
#        min-idle: 0
#    #连接超时时间（毫秒）
#    timeout: 30000
#    password: root
#    host: 192.168.10.101
#
#
#  ldap:
#    urls: ldap://localhost:389
#    base: dc=maxcrc,dc=com
#    username: cn=Manager,dc=maxcrc,dc=com
#    password: secret
#  datasource:
#    druid:
#      username: root
#      password: root
#      url: jdbc:mysql://192.168.10.101:3306/sell_mail?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&socketTimeout=10000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      connection-properties: config.decrypt=false;
#  devtools:
#    restart:
#      enabled : true
#      additional-paths : src/main/java
#      exclude : static/**,public/**
#server:
#  port: 8302
#mybatis:
#  mapper-locations: classpath :**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#async:
#  executor:
#    thread:
#      max_pool_size: 3
#      core_pool_size: 2
#      queue_capacity: 5
#      name:
#        prefix: importDate